// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlO_tg3_nf6YtWNoMot-ROh5ptNzTOIYs',
    appId: '1:735932095514:android:b10890c513d91ac888c5a3',
    messagingSenderId: '735932095514',
    projectId: 'lazy-reader-ai',
    storageBucket: 'lazy-reader-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACpd2AvoFU-2yOVGZCM2Kkh3NgrJpBTkQ',
    appId: '1:735932095514:ios:8835599b071e445888c5a3',
    messagingSenderId: '735932095514',
    projectId: 'lazy-reader-ai',
    storageBucket: 'lazy-reader-ai.appspot.com',
    androidClientId: '735932095514-mga8ijo6e134q2lm0tgl1ea54ofpf8fg.apps.googleusercontent.com',
    iosClientId: '735932095514-2vl64k4iba1ef79rgktb70fnarnr6ca6.apps.googleusercontent.com',
    iosBundleId: 'com.futurelabs.lazyreader',
  );
}
